cloud:
  aws:
    stack:
      auto: ${ENABLE_CLOUDWATCH_METRICS:false}
    region:
      auto: false
      static: eu-west-2

management:
  metrics:
    export:
      cloudwatch:
        enabled: ${ENABLE_CLOUDWATCH_METRICS:false}
        namespace: tis-trainee-reference
        batch-size: 20

server:
  port: 8205
  servlet:
    context-path: /reference

spring:
  data:
    mongodb:
      uri: mongodb://${DB_USER:admin}:${DB_PASSWORD:pwd}@${DB_HOST:localhost}:${DB_PORT:27017}/${DB_NAME:reference}?authSource=${AUTH_SOURCE:admin}
