mongock:
  migration-scan-package: uk.nhs.hee.tis.trainee.reference.changelog

server:
  port: 8205
  servlet:
    context-path: /reference

spring:
  data:
    mongodb:
      uri: mongodb://${DB_USER:admin}:${DB_PASSWORD:pwd}@${DB_HOST:localhost}:${DB_PORT:27017}/${DB_NAME:reference}?authSource=${AUTH_SOURCE:admin}

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${SENTRY_ENVIRONMENT:local}
