mongock:
  migration-scan-package: uk.nhs.hee.tis.trainee.reference.changelog

server:
  port: 8205
  servlet:
    context-path: /reference

spring:
  data:
    mongodb:
      uri: mongodb://${DB_USER:admin}:${DB_PASSWORD:pwd}@${DB_HOST:localhost}:${DB_PORT:27017}/${DB_NAME:reference}?authSource=${AUTH_SOURCE:admin}&replicaSet=rs0&readPreference=secondaryPreferred

sentry:
  dsn: ${SENTRY_DSN:}
  environment: ${ENVIRONMENT:local}

com:
  amazonaws:
    xray:
      emitters:
        daemon-address: ${AWS_XRAY_DAEMON_ADDRESS:}
