server:
  port: 8205

spring:
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: ${DB_NAME:reference}
      user: ${DB_USER:''}
      password: ${DB_PASSWORD:''}
