server:
  port: 8205
  servlet:
    context-path: /reference

spring:
  data:
    mongodb:
      uri: mongodb://${DB_USER:admin}:${DB_PASSWORD:pwd}@${DB_HOST:localhost}:${DB_PORT:27017}/${DB_NAME:reference}
