server:
  port: 8205
  servlet:
    context-path: /reference

spring:
  data:
    mongodb:
      uri: mongodb://${DB_HOST:localhost}:${DB_PORT:27017}
      database: ${DB_NAME:reference}
      username: ${DB_USER:admin}
      password: ${DB_PASSWORD:pwd}
